---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-legacy-dynamic  # Eventually this will be rebuilt or replaced
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.86.21
  share: /srv/shares/
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - async
  - noatime