---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Target clusters where this app should be deployed
patches:
  - target:
      kind: ApplicationSet
    patch: |
      - op: remove
        path: /spec/template/spec/syncPolicy/automated
      - op: add
        path: /spec/generators/0/matrix/generators/0
        value:
          list:
            elements:
              - server: https://kubernetes.default.svc
                shortName: lab
      - op: add
        path: /spec/generators/0/matrix/generators/0
        value:
          list:
            elements:
                - service: plex
                - service: prowlarr
                - service: radarr
                - service: sonarr
                - service: transmission
                - service: media-shares
      - op: replace
        path: /spec/template/spec/source/targetRevision
        value: develop
