---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 210Gi
  volumeName: nfs-downloads
  storageClassName: nfs-legacy-dynamic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  volumeName: nfs-media
  storageClassName: nfs-legacy-dynamic