---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads
spec:
  capacity:
    storage: 210Gi # Approximately 225 GB
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-legacy-dynamic
  nfs:
    path: /opt/htpc/downloads
    server: data.amolicob.cloud
  mountOptions:
    - nfsvers=4.1
    - async
    - noatime
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media
spec:
  capacity:
    storage: 15Ti # Approximately 16.1 terabytes
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-legacy-dynamic
  nfs:
    path: /opt/htpc/media
    server: data.amolicob.cloud
  mountOptions:
    - nfsvers=4.1
    - async
    - noatime
