---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: radarr
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: radarr
  template:
    metadata:
      labels:
        run: radarr
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: radarr
          image: linuxserver/radarr
          name: radarr
          ports:
            - containerPort: 7878
              name: webui
          startupProbe:
            httpGet:
              path: /ping
              port: webui
            periodSeconds: 30
          volumeMounts:
            - mountPath: "/config"
              name: config
            - mountPath: "/downloads"
              name: downloads
            - mountPath: "/media"
              name: media
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: nfs-downloads
        - name: media
          persistentVolumeClaim:
            claimName: nfs-media
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-iscsi
