---
# ISCSI data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-iscsi
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-static
  iscsi:
    targetPortal: amolicob.cloud:3260
    iqn: iqn.2025-02.cloud.amolicob:radarr
    lun: 1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-iscsi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: iscsi-static
  volumeName: radarr-config-iscsi
