---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-webui
spec:
  secretName: plex-webui
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - watch.amolicob.cloud
