---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-legacy-dynamic
---
# ISCSI data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-iscsi
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-static
  iscsi:
    targetPortal: 192.168.86.21:3260
    iqn: iqn.2025-02.cloud.amolicob:plex
    lun: 1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-iscsi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: iscsi-static
  volumeName: plex-config-iscsi
