---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-legacy-dynamic