---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/
  - helmchartconfig.yaml

patches:
  - target:
      kind: Certificate
      name: traefik-default
    patch: |
      - op: replace
        path: /spec/dnsNames/0
        value: "lab.amolicob.cloud"
