---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

images:
  - name: ghcr.io/ericgoedtel/mealwhisperer/mealwhisperer-api
    newName: depot.lab.amolicob.cloud/mealwhisperer-api
  - name: ghcr.io/ericgoedtel/mealwhisperer/mealwhisperer-frontend
    newName: depot.lab.amolicob.cloud/mealwhisperer-frontend

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/revisionHistoryLimit
        value: 2
      - op: replace
        path: /spec/replicas
        value: 0
