---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: kinokube-psql
  namespace: kinokube
spec:
  teamId: kinokube
  volume:
    size: 20Gi
    # class and group enable mounting psql storage from nfs
    storageClass: nfs-legacy-dynamic
    selector:
      matchLabels:
        project: kinokube
  numberOfInstances: 1
  users:
    eric:
      - superuser
      - createdb
    sonarr: []
  databases: # dbname: owner
    sonarr_main: sonarr
    sonarr_logs: sonarr
  postgresql:
    version: "17"
    parameters:
      password_encryption: scram-sha-256
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-postgresql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-legacy-dynamic
