---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../origin/ # The raw upstream manifests
  - kinokube.yaml # individual db cluster

patches:
  - path: configmap.yaml # global overrides for operator
