---
provider:
  name: cloudflare
logFormat: json
interval: 5m
sources:
  - service
  - ingress
  - traefik-proxy
env:
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: password
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: username
