---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr
spec:
  secretName: overseerr
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - ask.amolicob.cloud
