---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - target:
      kind: ApplicationSet
    patch: |
      - op: replace
        path: /metadata/name
        value: "cluster-addons"
      - op: replace
        path: /spec/template/spec/destination/namespace
        value: "kube-system"
