---
namespace: kinokube

resources:
  - ../../base

components:
  # - https://github.com/ericgoedtel/kinokube//components/overseerr?ref=ad36c7bb3f495efdf073a973703d259031e148f9
  - https://github.com/ericgoedtel/kinokube//components/plex?ref=79108b3055bd21999e560c5b102b1b219efdf816
  - https://github.com/ericgoedtel/kinokube//components/prowlarr?ref=79108b3055bd21999e560c5b102b1b219efdf816
  - https://github.com/ericgoedtel/kinokube//components/radarr?ref=79108b3055bd21999e560c5b102b1b219efdf816
  - https://github.com/ericgoedtel/kinokube//components/sonarr?ref=79108b3055bd21999e560c5b102b1b219efdf816
  - https://github.com/ericgoedtel/kinokube//components/transmission?ref=79108b3055bd21999e560c5b102b1b219efdf816
