---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - service: adguard
                  namespace: adguard
                - service: 1password
                  namespace: 1password
                - service: external-dns
                  namespace: external-dns
  template:
    metadata:
      name: "{{service}}-{{shortName}}"
      labels:
        app: "{{service}}"
        project: infrastructure
    spec:
      project: default # TODO: Is it worth it to create separate projects?
      source:
        repoURL: https://github.com/ericgoedtel/applications
        targetRevision: HEAD
        path: "apps/{{service}}/overlays/{{shortName}}"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
      ignoreDifferences:
        - kind: Secret
          name: op-credentials
          jsonPointers:
            - /data/1password-credentials.json
        - kind: Secret
          name: onepassword-token
          jsonPointers:
            - /data/token
