---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

# Patches specific to all infrastructure apps
patches:
  - target:
      kind: ApplicationSet
    patch: |
      - op: replace
        path: /metadata/name
        value: infrastructure
  - target:
      kind: ApplicationSet
    patch: |
      - op: add
        path: /spec/generators/0/matrix/generators/0
        value:
          list:
            elements:
                - service: adguard
                - service: 1password
                - service: external-dns
                - service: cert-manager
                - service: traefik
                - service: postgres-operator
