---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

images:
  - name: adguard/adguardhome
    digest: "sha256:633154b8e53689a5de756b5a1dc6afda03855ff4c84086c636a6cd67140523f8"