---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/revisionHistoryLimit
        value: 2
      - op: replace
        path: /spec/replicas
        value: 1
  # Patch in postgres configuration values. This may be portable since we're using in-cluster hostnames. Merge back upwards if possible
  - target:
      kind: ConfigMap
      name: sonarr
    path: configmap.yaml
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: SONARR__POSTGRES__PASSWORD
            valueFrom:
              secretKeyRef:
                name: sonarr.kinokube-psql.credentials.postgresql.acid.zalan.do
                key: password
