---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/revisionHistoryLimit
        value: 2
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/template/spec/volumes/3
        value:
          name: config
          persistentVolumeClaim:
            claimName: sonarr-config-iscsi
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/3
      - op: remove
        path: /spec/template/spec/volumes/0
  - target:
      # TODO: Move this to a label selector at some point
      kind: PersistentVolume
    patch: |
      - op: replace
        path: /spec/iscsi/targetPortal
        value: 192.168.86.45:3260
