---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-default
spec:
  secretName: traefik-default
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - amolicob.cloud
