---
# This doesn't actually do anything I am just documenting changes
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entrypoints.dns.address=:53/udp"
      - "--entrypoints.web.address=:8000"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
    ports:
      dns:
        port: 53
        expose:
          default: true
        protocol: UDP
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: amolicob.cloud
