---
resources:
  - ../../base/

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/revisionHistoryLimit
        value: 2
  - target:
      kind: StorageClass
    patch: |
      - op: replace
        path: /parameters
        value:
          server: 192.168.86.45
          share: /srv/shares/nfs
