---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-admin
spec:
  secretName: adguard-admin
  issuerRef:
    name: letsencrypt-dns-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - blackhole.amolicob.cloud
