---
# Forwards to the current cluster IP of adguard. May break if the service is reconstituted
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  forward.override: |
    forward . 10.43.3.24
