---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard

resources:
  - deployment.yaml
  - ingress.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
  - configmap.yaml
