---
# TODO: Maybe don't store this on a single node
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# TODO: Maybe don't store this on a single node
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi