---
# TODO: Exclude from argocd lifecycle when changes detected
# TODO: External secret operator from 1p?
apiVersion: v1
kind: Secret
metadata:
  name: adguardhome
type: Opaque
data:  # These will be updated in-cluster
  username: ""
  password: ""