---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # sync this before deploy 
data:
  SONARR__AUTH__ENABLED: "false"
  SONARR__AUTH__METHOD: "none"
  SONARR__AUTH__REQUIRED: "DisabledForLocalAddresses"
  SONARR__SERVER__URLBASE: "/sonarr"
  PUID: "65534" # nobody
  PGID: "65534"