---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sonarr
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sonarr
  template:
    metadata:
      labels:
        run: sonarr
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: sonarr
          env: []
          image: linuxserver/sonarr
          name: sonarr
          ports:
            - containerPort: 8989
              name: webui
          startupProbe:
            httpGet:
              path: /ping
              port: webui
            periodSeconds: 30
            failureThreshold: 10
          volumeMounts:
            - mountPath: "/config"
              name: config
            - mountPath: "/downloads"
              name: downloads
            - mountPath: "/media"
              name: media
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: nfs-downloads
        - name: media
          persistentVolumeClaim:
            claimName: nfs-media
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config-iscsi
