---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - resources.yaml
  - clusterissuer.yaml
  - onepassworditem.yaml

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
