---
# Source: connect/crds/onepassworditem-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: onepassworditems.onepassword.com
spec:
  group: onepassword.com
  names:
    kind: OnePasswordItem
    listKind: OnePasswordItemList
    plural: onepassworditems
    singular: onepassworditem
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: OnePasswordItem is the Schema for the onepassworditems API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: OnePasswordItemSpec defines the desired state of OnePasswordItem
              properties:
                itemPath:
                  type: string
              type: object
            status:
              description: OnePasswordItemStatus defines the observed state of OnePasswordItem
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        description:
                          Last time the condition transit from one status
                          to another.
                        format: date-time
                        type: string
                      message:
                        description:
                          Human-readable message indicating details about
                          last transition.
                        type: string
                      status:
                        description: Status of the condition, one of True, False, Unknown.
                        type: string
                      type:
                        description: Type of job condition, Completed.
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
              required:
                - conditions
              type: object
            type:
              description: "Kubernetes secret type. More info: https://kubernetes.io/docs/concepts/configuration/secret/#secret-types"
              type: string
          type: object
      served: true
      storage: true
      subresources:
        status: {}

---
# Source: connect/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onepassword-connect-operator
  namespace: 1password
  labels:
    helm.sh/chart: connect-1.17.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.7.3"
    app.kubernetes.io/managed-by: Helm
---
# Source: connect/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: onepassword-connect-operator
  labels:
    helm.sh/chart: connect-1.17.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.7.3"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - onepassword-connect-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - onepassword.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
# Source: connect/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onepassword-connect-operator
  labels:
    helm.sh/chart: connect-1.17.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.7.3"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: onepassword-connect-operator
  namespace: 1password
roleRef:
  kind: ClusterRole
  name: onepassword-connect-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: connect/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: 1password
  labels:
    app.kubernetes.io/component: connect
    helm.sh/chart: connect-1.17.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.7.3"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  selector:
    app: onepassword-connect
  ports:
    - port: 8081
      name: connect-sync
    - port: 8080
      name: connect-api
---
# Source: connect/templates/connect-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect
  namespace: 1password
  labels:
    app.kubernetes.io/component: connect
    helm.sh/chart: connect-1.17.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.7.3"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
        version: "1.7.3"
        app.kubernetes.io/component: connect
    spec:
      volumes:
        - name: shared-data
          emptyDir:
            {}
        - name: credentials
          secret:
            secretName: onepassword-connect
      tolerations:
        []
      containers:
        - name: connect-api
          image: 1password/connect-api:1.7.3
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 0.2
          env:
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  name: onepassword-connect
                  key: b64-json
            - name: OP_BUS_PORT
              value: "11220"
            - name: OP_BUS_PEERS
              value: localhost:11221
            - name: OP_HTTP_PORT
              value: "8080"
            - name: OP_LOG_LEVEL
              value: "info"            
          readinessProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: 8080
            initialDelaySeconds: 15
          
          livenessProbe:
            httpGet:
              path: /heartbeat
              scheme: HTTP
              port: 8080
            failureThreshold: 3
            periodSeconds: 30
            initialDelaySeconds: 15
          
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
        - name: connect-sync
          image: 1password/connect-sync:1.7.3
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
          resources:
            {}
          env:
            - name: OP_HTTP_PORT
              value: "8081"
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  name: onepassword-connect
                  key: b64-json
            - name: OP_BUS_PORT
              value: "11221"
            - name: OP_BUS_PEERS
              value: localhost:11220
            - name: OP_LOG_LEVEL
              value: "info"            
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
          
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8081
              scheme: HTTP
            failureThreshold: 3
            periodSeconds: 30
            initialDelaySeconds: 15
          
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
---
# Source: connect/templates/operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect-operator
  namespace: 1password
  labels:
    app.kubernetes.io/component: operator
    helm.sh/chart: connect-1.17.0
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.7.3"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onepassword-connect
  template:
    metadata:
      labels:
        name: onepassword-connect
        app.kubernetes.io/component: operator
    spec:
      tolerations:
        []
      serviceAccountName: onepassword-connect-operator
      containers:
        - name: onepassword-connect
          image: 1password/onepassword-operator:1.8.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
          command: [ "/manager" ]
          args: [ --zap-log-level=info]
          env:
            - name: WATCH_NAMESPACE
              value: 
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "onepassword-connect-operator"
            - name: OP_CONNECT_HOST
              value: "http://onepassword-connect:8080"
            - name: POLLING_INTERVAL
              value: "600"
            - name: OP_CONNECT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: onepassword-connect
                  key: token
            - name: AUTO_RESTART
              value: "false"
          resources:
            {}
