---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argocd
  name: base
spec:
  generators:
    - matrix:
        generators: []
  template:
    metadata:
      name: "{{service}}-{{shortName}}"
      labels:
        app: "{{service}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/ericgoedtel/applications
        targetRevision: main
        path: "apps/{{service}}/overlays/{{shortName}}"
      destination:
        server: "{{server}}"
        namespace: "{{service}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
