---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prowlarr
  template:
    metadata:
      labels:
        run: prowlarr
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: prowlarr
          image: linuxserver/prowlarr
          name: prowlarr
          ports:
            - containerPort: 9696
              name: webui
          startupProbe:
            httpGet:
              path: /ping
              port: webui
            periodSeconds: 30
          volumeMounts:
            - mountPath: "/config"
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-iscsi
