---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-legacy-dynamic
---
# ISCSI data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-iscsi
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-static
  volumeName: prowlarr-config-iscsi
  iscsi:
    targetPortal: 192.168.86.21:3260
    iqn: iqn.2025-02.cloud.amolicob:prowlarr
    lun: 1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-iscsi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: iscsi-static
  volumeName: prowlarr-config-iscsi
