---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ApplicationSet
    patch: |
      - op: add
        path: /spec/generators/0/matrix/generators/0
        value:
          list:
            elements:
              - server: https://kubernetes.default.svc
                shortName: live
