---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/revisionHistoryLimit
        value: 2
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      # TODO: Move this to a label selector at some point
      kind: PersistentVolume
    patch: |
      - op: replace
        path: /spec/iscsi/targetPortal
        value: 192.168.86.45:3260
