---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kinokube
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                # - service: overseerr  # TODO: Later
                - service: plex
                - service: prowlarr
                - service: radarr
                - service: sonarr
                - service: transmission
  template:
    metadata:
      name: "{{service}}-{{shortName}}"
      labels:
        app: "{{service}}"
        project: kinokube
    spec:
      project: default  # TODO: Is it worth it to create separate projects?
      source:
        repoURL: https://github.com/ericgoedtel/applications
        targetRevision: HEAD
        path: "apps/{{service}}"
      destination:
        server: "{{server}}"
        namespace: kinokube
      syncPolicy: {}  # TODO: Leave empty for now