---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kinokube
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - service: overseerr
                - service: plex
                - service: prowlarr
                - service: radarr
                - service: sonarr
                - service: transmission
template:
  metadata:
    name: "{{service}}-{{cluster}}"
    labels:
      app: "{{service}}"
      project: kinokube
  spec:
    project: kinokube  # TODO: Does this need to be created elsewhere?
    source:
      repoURL: git@github.com:ericgoedtel/applications
      targetRevision: HEAD
      path: "apps/{{service}}"
    destination:
      name: "{{cluster}}"
      namespace: kinokube
    syncPolicy: {}  # TODO: Leave empty for now