---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - target:
      kind: IngressRoute
      name: htpc
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: Host(`watch.lab.amolicob.cloud`)
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: lab.amolicob.cloud
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/revisionHistoryLimit
        value: 2
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      # TODO: Move this to a label selector at some point
      kind: PersistentVolume
    patch: |
      - op: replace
        path: /spec/iscsi/targetPortal
        value: 192.168.86.45:3260
  - target:
      kind: Certificate
    patch: |
      - op: replace
        path: /spec/dnsNames/0
        value: watch.lab.amolicob.cloud
